-- IBM Db2 13 for z/OS advanced-trigger template.
-- Replace every {{TOKEN}}. Configure the SQL processor to use ! as the outer
-- terminator. Do not add MODE DB2SQL: its absence selects an advanced trigger.
-- The definition and body APPLCOMPAT values are separate test inputs.

CREATE TRIGGER {{TRIGGER_SCHEMA}}.{{ADVANCED_TRIGGER}}
  VERSION {{TRIGGER_VERSION}}
  AFTER UPDATE OF {{WATCH_COLUMN}}
  ON {{SUBJECT_SCHEMA}}.{{SUBJECT_TABLE}}
  REFERENCING OLD ROW AS OLDROW NEW ROW AS NEWROW
  FOR EACH ROW
  QUALIFIER {{DEFAULT_QUALIFIER}}
  SQL PATH {{SQL_PATH}}
  APPLCOMPAT {{BODY_APPLCOMPAT}}
  WHEN ({{WHEN_CONDITION_USING_OLDROW_AND_NEWROW}})
  BEGIN ATOMIC
    DECLARE V_MATCH_COUNT INTEGER DEFAULT 0;
    DECLARE V_HANDLER_USED SMALLINT DEFAULT 0;
    DECLARE CONTINUE HANDLER FOR NOT FOUND
      SET V_HANDLER_USED = 1;

    SELECT COUNT(*)
      INTO V_MATCH_COUNT
      FROM {{LOOKUP_SCHEMA}}.{{LOOKUP_TABLE}}
     WHERE {{LOOKUP_KEY_COLUMN}} = NEWROW.{{SUBJECT_KEY_COLUMN}};

    IF V_MATCH_COUNT > 0 THEN
      INSERT INTO {{AUDIT_SCHEMA}}.{{AUDIT_TABLE}}
        ({{AUDIT_KEY_COLUMN}}, {{AUDIT_OLD_COLUMN}}, {{AUDIT_NEW_COLUMN}})
        VALUES
        (NEWROW.{{SUBJECT_KEY_COLUMN}},
         OLDROW.{{WATCH_COLUMN}},
         NEWROW.{{WATCH_COLUMN}});
    ELSE
      SIGNAL SQLSTATE '75001'
        SET MESSAGE_TEXT = '{{NO_LOOKUP_ROW_MESSAGE}}';
    END IF;

    GET CURRENT DIAGNOSTICS V_MATCH_COUNT = ROW_COUNT;
    SET V_HANDLER_USED = V_HANDLER_USED;
  END!

-- Verification targets:
--   SYSIBM.SYSTRIGGERS.SQLPL = 'Y' and VERSION/ACTIVE are expected.
--   SYSIBM.SYSPACKAGE.TYPE = '1' and APPLCOMPAT matches {{BODY_APPLCOMPAT}}.
--   SYSIBM.SYSENVIRONMENT records definition-processing APPLCOMPAT separately.
