-- IBM Db2 13 for z/OS native SQL procedure template.
-- Replace every {{TOKEN}}. Configure the SQL processor to use ! as the outer
-- terminator because the compound body contains semicolons.
-- Do not add FENCED or EXTERNAL: their absence selects a native SQL procedure.
-- Set {{PACKAGE_OWNER_TYPE}} to AS USER or AS ROLE.

CREATE PROCEDURE {{PROCEDURE_SCHEMA}}.{{PROCEDURE_NAME}}
  (IN P_KEY INTEGER,
   IN P_DELTA DECIMAL(15,2),
   OUT P_ROW_COUNT INTEGER)
  VERSION {{PROCEDURE_VERSION}}
  LANGUAGE SQL
  SPECIFIC {{PROCEDURE_SCHEMA}}.{{PROCEDURE_SPECIFIC_NAME}}
  NOT DETERMINISTIC
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  DYNAMIC RESULT SETS 0
  COMMIT ON RETURN NO
  INHERIT SPECIAL REGISTERS
  QUALIFIER {{DEFAULT_QUALIFIER}}
  SQL PATH {{SQL_PATH}}
  PACKAGE OWNER {{PACKAGE_OWNER}} {{PACKAGE_OWNER_TYPE}}
  APPLCOMPAT {{BODY_APPLCOMPAT}}
  BEGIN
    DECLARE V_ROW_COUNT INTEGER DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
      SET P_ROW_COUNT = -1;

    UPDATE {{TARGET_SCHEMA}}.{{TARGET_TABLE}}
       SET {{AMOUNT_COLUMN}} = {{AMOUNT_COLUMN}} + P_DELTA
     WHERE {{KEY_COLUMN}} = P_KEY;

    GET DIAGNOSTICS V_ROW_COUNT = ROW_COUNT;
    SET P_ROW_COUNT = V_ROW_COUNT;
  END!

-- Verification targets:
--   SYSIBM.SYSROUTINES.ROUTINETYPE = 'P', ORIGIN = 'N', VERSION/ACTIVE match.
--   SYSIBM.SYSPARMS preserves parameter order, mode, type, and CCSID.
--   SYSIBM.SYSPACKAGE.TYPE = 'N', with matching VERSION and APPLCOMPAT.
--   SYSIBM.SYSPACKDEP records body dependencies with DTYPE = 'N'.
