-- Explicit Db2-managed object stack for an OFS round-trip test.
-- IBM source IDs: ibm-create-stogroup, ibm-create-database,
-- ibm-create-tablespace, ibm-create-table, ibm-create-index.
-- Required tokens: STOGROUP, VCAT, DATABASE, TABLESPACE, SCHEMA, TABLE,
-- INDEX_SCHEMA, INDEX, TABLE_BP, INDEX_BP.
-- Prerequisites: active buffer pools; authorization; SMS accepts '*'.

CREATE STOGROUP {{STOGROUP}}
  VOLUMES ('*')
  VCAT {{VCAT}};

CREATE DATABASE {{DATABASE}}
  STOGROUP {{STOGROUP}}
  BUFFERPOOL {{TABLE_BP}}
  INDEXBP {{INDEX_BP}}
  CCSID EBCDIC;

CREATE TABLESPACE {{TABLESPACE}}
  IN {{DATABASE}}
  BUFFERPOOL {{TABLE_BP}}
  MAXPARTITIONS 16
  NUMPARTS 1
  DSSIZE 4 G
  SEGSIZE 32
  CCSID EBCDIC
  CLOSE NO
  COMPRESS YES FIXEDLENGTH
  DEFINE YES
  FREEPAGE 0
  PCTFREE 5 FOR UPDATE 5
  LOCKMAX SYSTEM
  LOCKSIZE ANY
  LOGGED
  TRACKMOD YES
  USING STOGROUP {{STOGROUP}}
    PRIQTY -1
    SECQTY -1
    ERASE NO;

CREATE TABLE {{SCHEMA}}.{{TABLE}}
  (
    OBJECT_ID BIGINT NOT NULL,
    OBJECT_NAME VARCHAR(128) NOT NULL,
    OBJECT_STATUS CHAR(1) NOT NULL WITH DEFAULT,
    CHANGED_AT TIMESTAMP(12) NOT NULL WITH DEFAULT,
    CONSTRAINT {{TABLE}}_CK1
      CHECK (OBJECT_STATUS IN ('A', 'I'))
  )
  IN {{DATABASE}}.{{TABLESPACE}}
  AUDIT NONE
  DATA CAPTURE NONE
  NOT VOLATILE CARDINALITY
  APPEND NO;

CREATE UNIQUE INDEX {{INDEX_SCHEMA}}.{{INDEX}}
  ON {{SCHEMA}}.{{TABLE}}
    (OBJECT_ID ASC, OBJECT_NAME ASC)
  CLUSTER
  NOT PADDED
  USING STOGROUP {{STOGROUP}}
    PRIQTY -1
    SECQTY -1
    ERASE NO
  FREEPAGE 0
  PCTFREE 10
  GBPCACHE CHANGED
  DEFINE YES
  COMPRESS NO
  BUFFERPOOL {{INDEX_BP}}
  CLOSE YES
  DEFER NO
  COPY NO;

COMMIT;
